services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: saver_tounsi

